$ver = "0.11"
$fullver = "${ver}.0.0"

$basedir = "$pwd"
$utilsdir = "C:\utils"
$hg = "C:\Program Files\TortoiseHg\hg.exe"
$msbuild = "c:\windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe"
$vcsexpress = "C:\Program Files\Microsoft Visual Studio 10.0\Common7\IDE\VCSExpress.exe"
$signingkey = "${pwd}\DiscUtilsSigningKey.snk"
$zip = "${utilsdir}\7za.exe"
$fxcop = "C:\Program Files (x86)\Microsoft Visual Studio 11.0\Team Tools\Static Analysis Tools\FxCop\fxcopcmd.exe"
