//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscUtils {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscUtils.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;value&gt;
        ///  &lt;struct&gt;
        ///    &lt;member&gt;
        ///      &lt;name&gt;version&lt;/name&gt;
        ///      &lt;value&gt;
        ///        &lt;struct&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;hostname&lt;/name&gt;
        ///            &lt;value&gt;cheesy-2&lt;/value&gt;
        ///          &lt;/member&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;date&lt;/name&gt;
        ///            &lt;value&gt;2008-11-08&lt;/value&gt;
        ///          &lt;/member&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;product_version&lt;/name&gt;
        ///            &lt;value&gt;1.0.0&lt;/value&gt;
        ///          &lt;/member&gt;
        ///          &lt;member&gt;
        ///            &lt;name&gt;product_brand&lt;/name&gt;
        ///            &lt;va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XVA_ova_base {
            get {
                return ResourceManager.GetString("XVA_ova_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                               &lt;value&gt;{0}&lt;/value&gt;
        ///.
        /// </summary>
        internal static string XVA_ova_ref {
            get {
                return ResourceManager.GetString("XVA_ova_ref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;SR&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XVA_ova_sr {
            get {
                return ResourceManager.GetString("XVA_ova_sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;VBD&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XVA_ova_vbd {
            get {
                return ResourceManager.GetString("XVA_ova_vbd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;VDI&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XVA_ova_vdi {
            get {
                return ResourceManager.GetString("XVA_ova_vdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to             &lt;value&gt;
        ///              &lt;struct&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;class&lt;/name&gt;
        ///                  &lt;value&gt;VM&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;id&lt;/name&gt;
        ///                  &lt;value&gt;{0}&lt;/value&gt;
        ///                &lt;/member&gt;
        ///                &lt;member&gt;
        ///                  &lt;name&gt;snapshot&lt;/name&gt;
        ///                  &lt;value&gt;
        ///                    &lt;struct&gt;
        ///                      &lt;member&gt;
        ///                        &lt;name&gt;uuid&lt;/name&gt;
        ///               [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string XVA_ova_vm {
            get {
                return ResourceManager.GetString("XVA_ova_vm", resourceCulture);
            }
        }
    }
}
